### ISSUE TITLE
What are you using this for?

### ISSUE THREAD

**Issue by NeuroForLunch** [kelu124/max14866#1]
This is quite interesting. What use cases are there?

**Comment by kelu124** [comment]
Ultrasound ;) Linked with the un0rick boarc

**Comment by kelu124** [comment]
Check https://github.com/kelu124/echomods/blob/master/matty/20210424a/mux.png for insertion loss

**Comment by kelu124** [comment]
@NeuroForLunch would that answer your question / able to close this issue?
